<a href="https://colab.research.google.com/github/Pratikshapawar-star/python-internship-practice-code/blob/main/Day3_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
mylist=[[1,2,3],[4,5,6],[7,8,9]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.random.rand(5)  #uniform distribution of random values

array([0.04810734, 0.8121561 , 0.29808653, 0.32498266, 0.91718621])

In [ ]:
np.random.rand(4,4) #create 2D array of random values

array([[0.96175311, 0.6073085 , 0.95190146, 0.92823156],
       [0.06232761, 0.17015505, 0.01040862, 0.92872498],
       [0.97387699, 0.20480041, 0.88641065, 0.89927785],
       [0.36231232, 0.36526226, 0.56624371, 0.70847603]])

In [ ]:
np.random.randn(4) #std.normal  distribution , centered

array([ 0.5739407 ,  0.07485339, -0.57760968,  0.21322754])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
import pandas as pd
import numpy as np

data={
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass","Nuclear"],
    "Energy Consumption (MWh)" : [1200,np.nan,2900,2500,np.nan,3200],
    "Cost(Million $)":[200,400,np.nan,150,250,np.nan]
}
energy_df=pd.DataFrame(data)

print("Original energy data with Missing values:")
print(energy_df)

Original energy data with Missing values:
  Energy Source  Energy Consumption (MWh)  Cost(Million $)
0         Solar                    1200.0            200.0
1          Wind                       NaN            400.0
2    Hydropower                    2900.0              NaN
3    Geothermal                    2500.0            150.0
4       Biomass                       NaN            250.0
5       Nuclear                    3200.0              NaN


In [ ]:
energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean(),inplace=True)

energy_df["Cost(Million $)"].fillna(energy_df["Cost(Million $)"].mean(),inplace=True)

print("\nData After Inputing Missing values with Mean:")
print(energy_df)


Data After Inputing Missing values with Mean:
  Energy Source  Energy Consumption (MWh)  Cost(Million $)
0         Solar             -1.637804e+00        -0.534522
1          Wind              2.775558e-17         1.603567
2    Hydropower              5.896096e-01         0.000000
3    Geothermal              6.551218e-02        -1.069045
4       Biomass              2.775558e-17         0.000000
5       Nuclear              9.826827e-01         0.000000


/tmp/ipython-input-3165957864.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean(),inplace=True)
/tmp/ipython-input-3165957864.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, w

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
energy_df[['Energy Consumption (MWh)',"Cost(Million $)"]] = scaler.fit_transform(
    energy_df[['Energy Consumption (MWh)',"Cost(Million $)"]])

print("\nData After Normalization(Min-Max Scaling):")
print(energy_df)



Data After Normalization(Min-Max Scaling):
  Energy Source  Energy Consumption (MWh)  Cost(Million $)
0         Solar                     0.000              0.2
1          Wind                     0.625              1.0
2    Hydropower                     0.850              0.4
3    Geothermal                     0.650              0.0
4       Biomass                     0.625              0.4
5       Nuclear                     1.000              0.4


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
energy_df[["Energy Consumption (MWh)","Cost(Million $)"]] = scaler.fit_transform(
    energy_df[["Energy Consumption (MWh)","Cost(Million $)"]])

print("\nData After Normalization(Standard Scaling):")
print(energy_df)


Data After Normalization(Standard Scaling):
  Energy Source  Energy Consumption (MWh)  Cost(Million $)
0         Solar                 -2.005893    -6.546537e-01
1          Wind                  0.000000     1.963961e+00
2    Hydropower                  0.722121     1.817029e-16
3    Geothermal                  0.080236    -1.309307e+00
4       Biomass                  0.000000     1.817029e-16
5       Nuclear                  1.203536     1.817029e-16
